services:
  - type: web
    name: my-flask-app  # Change this to your desired service name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Adjust if your app is in a subdirectory
    autoDeploy: true
